# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "php:7.1"

# Configuration of the build of the application.
build:
    flavor: composer

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysqldb:mysql"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "web"
            # The front-controller script to send non-static requests to.
            passthru: "/index.php"
            # Wordpress has multiple roots (wp-admin) so the following is required
            index:
                - "index.php"
            # The number of seconds whitelisted (static) content should be cached.
            expires: 600
            scripts: true
            allow: true
            rules:
                '^/wp/xmlrpc\.php$':
                    scripts: false
                    allow: false
        "/wp-content":
            root: "web/wp-content"
            scripts: false
            allow: false
            rules:
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf|pdf)$':
                    allow: true
        "/wp-content/themes":
           root: "web/wp-content/themes"
           scripts: true
           allow: true
        "/wp-content/plugins":
           root: "web/wp-content/plugins"
           scripts: true
           allow: true 

# The size of the persistent disk of the application (in MB).
disk: 2048

dependencies:
    php:
        wp-cli/wp-cli: "^1.1"
        psy/psysh: "^0.8.4"

# The mounts that will be performed when the package is deployed.
mounts:
    "/web/wp-content": "shared:files/wp-content"

hooks:
    deploy: |
        rsync -r web/wp/wp-content/* web/wp-content/
