# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{all}/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true

      # Base the cache on the session cookies. Ignore all other cookies.
      cookies:
          - '/^wordpress_logged_in_/'
          - '/^wordpress_sec_/'
          - '/PHPSESSID/'
          - 'wordpress_test_cookie'
          - '/^wp-postpass_/'
          - '/^woocommerce_/'
          - '/^wp_woocommerce_/'

"https://www.{all}/":
    type: redirect
    to: "https://{all}/"

"https://{all}/wp/wp-login.php?action=rp*":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: false
